#set_property PACKAGE_PIN F12 [get_ports O_CLK_SCIENCE_01_0]
###set_property PACKAGE_PIN L7  [get_ports O_SCIENCE_CTRL_01_0]
##set_property PACKAGE_PIN T8  [get_ports {O_DEMUX_C0_0[1]}]
##set_property PACKAGE_PIN N7  [get_ports {O_DEMUX_C0_0[0]}]
##set_property PACKAGE_PIN AC2 [get_ports {O_DEMUX_C1_0[1]}]
##set_property PACKAGE_PIN AB6 [get_ports {O_DEMUX_C1_0[0]}]
##set_property PACKAGE_PIN L3  [get_ports O_CLK_SCIENCE_23_0]
#set_property PACKAGE_PIN F7 [get_ports O_SCIENCE_CTRL_23_0]
#set_property PACKAGE_PIN R7 [get_ports {O_DEMUX_C2_0[1]}]
#set_property PACKAGE_PIN U9 [get_ports {O_DEMUX_C2_0[0]}]
#set_property PACKAGE_PIN AC7 [get_ports {O_DEMUX_C3_0[0]}]
#set_property PACKAGE_PIN AC9 [get_ports {O_DEMUX_C3_0[1]}]


#set_property IOSTANDARD LVCMOS18 [get_ports O_CLK_SCIENCE_01_0]
###set_property IOSTANDARD LVCMOS18 [get_ports O_SCIENCE_CTRL_01_0]
##set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C0_0[1]}]
##set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C0_0[0]}]
##set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C1_0[1]}]
##set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C1_0[0]}]
##set_property IOSTANDARD LVCMOS18 [get_ports O_CLK_SCIENCE_23_0]
#set_property IOSTANDARD LVCMOS18 [get_ports O_SCIENCE_CTRL_23_0]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C2_0[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C2_0[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C3_0[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_DEMUX_C3_0[0]}]

set_property PACKAGE_PIN AC4 [get_ports {O_CLK_SCIENCE_01_clk_p[0]}]
set_property PACKAGE_PIN L7  [get_ports {O_SCIENCE_CTRL_01_clk_p[0]}]
set_property PACKAGE_PIN N7  [get_ports {O_DEMUX_C0_clk_p[0]}]
set_property PACKAGE_PIN R8  [get_ports {O_DEMUX_C0_clk_p[1]}]
set_property PACKAGE_PIN AB6 [get_ports {O_DEMUX_C1_clk_p[0]}]
set_property PACKAGE_PIN AB2 [get_ports {O_DEMUX_C1_clk_p[1]}]

set_property PACKAGE_PIN L3  [get_ports {O_CLK_SCIENCE_23_clk_p[0]}]
set_property PACKAGE_PIN G8  [get_ports {O_SCIENCE_CTRL_23_clk_p[0]}]
set_property PACKAGE_PIN U9  [get_ports {O_DEMUX_C2_clk_p[0]}]
set_property PACKAGE_PIN R7  [get_ports {O_DEMUX_C2_clk_p[1]}]
set_property PACKAGE_PIN AB7 [get_ports {O_DEMUX_C3_clk_p[0]}]
set_property PACKAGE_PIN AC9 [get_ports {O_DEMUX_C3_clk_p[1]}]

set_property IOSTANDARD LVDS [get_ports {O_CLK_SCIENCE_01_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {O_SCIENCE_CTRL_01_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C0_clk_p[1]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C0_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C1_clk_p[1]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C1_clk_p[0]}]

set_property IOSTANDARD LVDS [get_ports {O_CLK_SCIENCE_23_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {O_CLK_SCIENCE_23_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports {O_SCIENCE_CTRL_23_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C2_clk_p[1]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C2_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C3_clk_p[1]}]
set_property IOSTANDARD LVDS [get_ports {O_DEMUX_C3_clk_p[0]}]





